name: Dev - Build and Deploy
run-name: Dev - Build and Deploy by ${{ github.actor }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  OUTPUT_PATH: "."
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  BUILD_NAME: "functionapp-${{ github.run_number }}"
  ARTIFACT_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}"

jobs:
  build:
    name: "Build Using"
    uses: big-ricardo/esteiras-reutilizaveis/.github/workflows/azure-functions-build.yml@main
    with:
      node-version: ${{ vars.NODE_VERSION }}
      repo-path: "."

  deploy-staging:
    name: "Deploy to QA"
    needs: build
    uses: big-ricardo/esteiras-reutilizaveis/.github/workflows/azure-functions-deploy-only.yml@main
    with:
      artifact-name: "${{ github.event.repository.name }}-${{ github.run_id }}"
      app-name: "functionApp-Luis"
      environment: "dev"
    secrets: inherit
