name: DEV - Build and Deploy
run-name: DEV - Build and Deploy by ${{ github.actor }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  OUTPUT_PATH: "."
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  BUILD_NAME: "functionapp-${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Npm"
        shell: bash
        run: |
          pushd './${{ env.OUTPUT_PATH }}'
          npm install
          npm run build --if-present

      - name: "Run tests"
        shell: bash
        run: |
          pushd './${{ env.OUTPUT_PATH }}'
          npm run test

      - name: "Install dependencies for production"
        shell: bash
        run: |
          pushd './${{ env.OUTPUT_PATH }}'
          npm install --production

      - name: "Zip build artifact"
        shell: bash
        run: |
          pushd './${{ env.OUTPUT_PATH }}'
          zip -r ${{env.BUILD_NAME}}.zip *

      - name: "Upload Artifact of Function App"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}
          path: ${{ env.OUTPUT_PATH }}/${{env.BUILD_NAME}}.zip
          if-no-files-found: error
          retention-days: 1

  deploy-dev:
    name: "Deploy Function App to DEV"
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
      url: ${{ steps.deployFunctionApp.outputs.app-url}}
    steps:
      - name: "Download Artifact of Function App"
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}

      - name: "Unzip Artifact of Function App"
        shell: bash
        run: |
          unzip ${{env.BUILD_NAME}}.zip -d .
          rm ${{env.BUILD_NAME}}.zip

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: deployFunctionApp
        with:
          app-name: "functionApp-Luis"
          slot-name: "production"
          package: ${{ env.OUTPUT_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
