name: Create release

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-tag:
    name: Create Tag and Release to Production
    permissions:
      contents: write
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Extract branch tag
        id: tag
        run: |
          BRANCH=${{ github.head_ref }}
          TAG="${BRANCH//release\//""}"
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT
  release:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    needs:
      - create-tag
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.create-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ env.TAG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
