name: Prod - Build and Deploy
run-name: Prod - Build and Deploy by ${{ github.actor }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OUTPUT_PATH: "."
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  BUILD_NAME: "functionapp-${{ github.run_number }}"
  ARTIFACT_NAME: "${{ github.event.repository.name }}-${{ github.run_id }}"

jobs:
  build:
    name: "Build Using"
    uses: big-ricardo/esteiras-reutilizaveis/.github/workflows/azure-functions-build.yml@main
    with:
      node-version: ${{ vars.NODE_VERSION }}
      repo-path: "."

  deploy-staging:
    name: "Deploy to QA"
    needs: build
    uses: big-ricardo/esteiras-reutilizaveis/.github/workflows/azure-functions-deploy-only.yml@main
    with:
      artifact-name: "${{ github.event.repository.name }}-${{ github.run_id }}"
      app-name: "functionApp-Luis"
      environment: "qa"
    secrets: inherit

  deploy-production:
    needs: deploy-staging
    name: "Deploy to PROD"
    uses: big-ricardo/esteiras-reutilizaveis/.github/workflows/azure-functions-deploy-only.yml@main
    with:
      artifact-name: "${{ github.event.repository.name }}-${{ github.run_id }}"
      app-name: "functionApp-Luis"
      environment: "prod"
    secrets: inherit

  create-pr:
    name: "Create Pull Request"
    runs-on: ubuntu-latest
    needs: deploy-production
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
      - name: "Create Pull Request ${{ github.ref_name }} -> ${{ github.event.repository.default_branch }}"
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Deployed] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Enable Pull Request Auto Merge"
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge
